#!/bin/sh
# postinst script for JADAPTIVE OpenSSH Keyserver
#
# see: dh_installdeb(1)

# Source debconf library.
. /usr/share/debconf/confmodule

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
    configure)
		
    echo "\n\n# DO NOT CHANGE\nMACHINE_ID=`mktemp -u XXXXXXXXXXXXXXXXXXXXXXXX`" >> /etc/default/jadaptive-keyserver
      
	version_raw=`ssh -V 2>&1`
	major_version=`echo "${version_raw}" | sed 's/^.*_\([0-9]\)\.[0-9].*$/\1/'`
	minor_version=`echo "${version_raw}" | sed 's/^.*_[0-9]\.\([0-9]\).*$/\1/'`
	    
	if [ "$major_version" -le 6 ]; then
	    if [ "$major_version" -lt 8 ]; then
	        db_input high jadaptive/openssh_warning || true
	        db_go
	    fi
	fi

	 
	sed -i 's_#AuthorizedKeysCommand none_AuthorizedKeysCommand /usr/bin/keyserver-authorized-keys %h %u_g' /etc/ssh/sshd_config 	
	sed -i 's_#AuthorizedKeysCommandUser nobody_AuthorizedKeysCommandUser %u_g' /etc/ssh/sshd_config
	/etc/init.d/ssh reload
	
    ;;
    
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0



